SELECT
    UPDATE_TIME = FORMAT(P.UPDT_DT_TM, "YYYY-MM-DD HH:MM:SS")
    , END_DATE = FORMAT(P.END_EFFECTIVE_DT_TM, "YYYY-MM-DD HH:MM:SS")
    , P.USERNAME
    , P.NAME_FIRST
    , P.NAME_LAST
    , P.ACTIVE_IND
    , E.DIRECTORY_IND
    , P.UPDT_ID
    , P.UPDT_TASK
    , P.UPDT_CNT
    , P.PHYSICIAN_IND

FROM
    PRSNL	P
    ,(
        LEFT JOIN EA_USER E ON
        E.USERNAME = P.USERNAME
    )

PLAN
	P
;WHERE
    ;ENTER THE USER NAMES YOU WANT TO HAVE A LOOK AT BELOW.
;    P.USERNAME IN ("HOMERS8", "HOMERS9", "KARADUH", "WHITTLJ2")

JOIN
	E

ORDER BY
	P.UPDT_DT_TM DESC

WITH
	TIME = 10
    , MAXREC=3000
