SELECT ;DISTINCT	; USER EXTRACT SCRIPT	
	USER_LAST_UPDATE = FORMAT(P.UPDT_DT_TM, "YYYY-MM-DD HH:MM:SS")
	, P.USERNAME

	, END_DATE = FORMAT(P.END_EFFECTIVE_DT_TM, "YYYY-MM-DD HH:MM:SS")

	, USER_LAST_UPDATER =
		IF(P.PERSON_ID > 0 AND P.UPDT_ID = 0) "0"	
		ELSE P_UPDATE.NAME_FULL_FORMATTED	
		ENDIF

	, CREDENTIAL = UAR_GET_CODE_DISPLAY(CRED.CREDENTIAL_CD)

	, ORGANISTION = ORG.ORG_NAME	

	, USER_CREATE = FORMAT(P.CREATE_DT_TM, "YYYY-MM-DD HH:MM:SS")	

	, USER_CREATOR = 
		IF(P.PERSON_ID > 0 AND P.CREATE_PRSNL_ID = 0) "0"	
		ELSE P_CREATE.NAME_FULL_FORMATTED	
		ENDIF	

	, P.ACTIVE_IND	

	, BEG_DATE = FORMAT(P.BEG_EFFECTIVE_DT_TM, "YYYY-MM-DD HH:MM:SS")	     

	, P.NAME_FIRST	

	, P.NAME_LAST	

	, P.NAME_FULL_FORMATTED	

	, POSITION = UAR_GET_CODE_DISPLAY(P.POSITION_CD)

	, PRSNL_ID = P.PERSON_ID

	, ORG_COUNT = COUNT (DISTINCT P_ORG_R.ORGANIZATION_ID) OVER (PARTITION BY P.PERSON_ID)	

	, ORG_LAST_UPDATE = FORMAT(P_ORG_R .UPDT_DT_TM, "YYYY-MM-DD HH:MM:SS")	

	, ORG_LAST_UPDATER = 
		IF(P_ORG_R.PRSNL_ORG_RELTN_ID > 0 AND P_ORG_R .UPDT_ID = 0) "0"	
		ELSE P_P_ORG_R .NAME_FULL_FORMATTED	
		ENDIF	

	, PRSNL_ORG_RELTN_ID =
		IF(P_ORG_R.PRSNL_ORG_RELTN_ID > 0) CNVTSTRING(P_ORG_R.PRSNL_ORG_RELTN_ID)	
		ELSE ""	
		ENDIF	

	, ORG_GROUP = ORG_S.NAME	

	, ORG_GROUP_COUNT = COUNT (DISTINCT P_ORG_SET_R.ORG_SET_ID) OVER (PARTITION BY P.PERSON_ID)	

	, ORG_GRP_LAST_UPDATE = FORMAT(P_ORG_SET_R.UPDT_DT_TM, "YYYY-MM-DD HH:MM:SS")	

	, ORG_GRP_LAST_UPDATER =
		IF(P_ORG_SET_R.ORG_SET_PRSNL_R_ID > 0 AND P_ORG_SET_R .UPDT_ID = 0) "0"	
		ELSE P_P_ORG_SET_R .NAME_FULL_FORMATTED	
		ENDIF	

	, ORG_SET_PRSNL_R_ID =
		IF(P_ORG_SET_R.ORG_SET_PRSNL_R_ID > 0) CNVTSTRING(P_ORG_SET_R.ORG_SET_PRSNL_R_ID)	
		ELSE ""	
		ENDIF		

	, CRED_COUNT = COUNT (DISTINCT CRED.CREDENTIAL_CD) OVER (PARTITION BY P.PERSON_ID)	

	, CRED_LAST_UPDATE = FORMAT(CRED.UPDT_DT_TM, "YYYY-MM-DD HH:MM:SS")	

	, CRED_LAST_UPDATER =
		IF(CRED.CREDENTIAL_ID > 0 AND CRED.UPDT_ID = 0) "0"	
		ELSE P_CRED.NAME_FULL_FORMATTED	
		ENDIF	

	, CREDENTIAL_ID =
		IF(CRED.CREDENTIAL_ID > 0) CNVTSTRING(CRED.CREDENTIAL_ID)	
		ELSE ""	
		ENDIF	
		
FROM
	PRSNL P	
	, (LEFT JOIN PRSNL P_CREATE ON P.CREATE_PRSNL_ID = P_CREATE.PERSON_ID)

	, (LEFT JOIN PRSNL P_UPDATE ON P.UPDT_ID = P_UPDATE.PERSON_ID)

	, (LEFT JOIN PRSNL_ORG_RELTN P_ORG_R ON P_ORG_R.PERSON_ID = P.PERSON_ID	
		AND P_ORG_R.ACTIVE_IND = 1	
		AND P_ORG_R.BEG_EFFECTIVE_DT_TM < SYSDATE	
		AND P_ORG_R.END_EFFECTIVE_DT_TM > SYSDATE	
	)

	, (LEFT JOIN PRSNL P_P_ORG_R ON P_P_ORG_R.PERSON_ID = P_ORG_R .UPDT_ID)

	, (LEFT JOIN ORGANIZATION ORG ON ORG.ORGANIZATION_ID = P_ORG_R.ORGANIZATION_ID)

	, (LEFT JOIN ORG_SET_PRSNL_R P_ORG_SET_R ON P_ORG_SET_R.PRSNL_ID = P.PERSON_ID	
		AND P_ORG_SET_R.ACTIVE_IND = 1	
		AND P_ORG_SET_R.BEG_EFFECTIVE_DT_TM < SYSDATE	
		AND P_ORG_SET_R.END_EFFECTIVE_DT_TM > SYSDATE	
	)

	, (LEFT JOIN PRSNL P_P_ORG_SET_R ON P_P_ORG_SET_R.PERSON_ID = P_ORG_SET_R .UPDT_ID)

	, (LEFT JOIN ORG_SET ORG_S ON ORG_S.ORG_SET_ID = P_ORG_SET_R.ORG_SET_ID)

	, (LEFT JOIN CREDENTIAL CRED ON CRED.PRSNL_ID = P.PERSON_ID	
		AND CRED.ACTIVE_IND = 1	
		AND CRED.BEG_EFFECTIVE_DT_TM < SYSDATE	
		AND CRED.END_EFFECTIVE_DT_TM > SYSDATE	
	)

	, (LEFT JOIN PRSNL P_CRED ON P_CRED.PERSON_ID = CRED .UPDT_ID)	
		
PLAN	P	
WHERE
	P.PERSON_ID != 0	
JOIN	P_CREATE	
JOIN	P_UPDATE	
JOIN	P_ORG_R	
JOIN	P_P_ORG_R	
JOIN	ORG ;WHERE ORG.ORG_NAME= "WHS Footscray Hospital"
JOIN	P_ORG_SET_R	
JOIN	P_P_ORG_SET_R	
JOIN	ORG_S	
JOIN	CRED	
JOIN	P_CRED	
		
ORDER BY
	P.UPDT_DT_TM DESC		

		
WITH		
	TIME = 50	
	, MAXREC = 1000
