SELECT
	CLINICAL_EVENT.EVENT_ID
    , CLINICAL_EVENT.PARENT_EVENT_ID
    , CLINICAL_EVENT.DEVICE_FREE_TXT
    , CLINICAL_EVENT.ENCNTR_ID
    , CLINICAL_EVENT.PERSON_ID
    , CLINICAL_EVENT.EVENT_START_DT_TM
    , PERSON.PERSON_ID
    , PERSON.NAME_FIRST
    , PERSON.NAME_LAST
    , ENCNTR_EVENT_SET_IO.ENCNTR_ID
    , ENCNTR_EVENT_SET_IO.PERSON_ID
    , ENCOUNTER.LOC_FACILITY_CD
    , ENCOUNTER.ENCNTR_ID
;    , CODE_VALUE.CODE_VALUE
;    , CODE_VALUE.DISPLAY
;    , CODE_VALUE.DISPLAY_KEY

FROM
    CLINICAL_EVENT
    , 
    (LEFT JOIN ENCOUNTER ON
        CLINICAL_EVENT.ENCNTR_ID =
        ENCOUNTER.ENCNTR_ID
    ),
    (LEFT JOIN PERSON ON
        PERSON.PERSON_ID =
        CLINICAL_EVENT.PERSON_ID
    ),
    (LEFT JOIN ENCNTR_EVENT_SET_IO ON
        ENCNTR_EVENT_SET_IO.ENCNTR_ID =
        ENCOUNTER.ENCNTR_ID
    )

PLAN
    CLINICAL_EVENT

JOIN ENCOUNTER
JOIN PERSON
JOIN ENCNTR_EVENT_SET_IO

WITH
    MAXREC=1000
    , TIME=20