SELECT 
	OC.PRIMARY_MNEMONIC
	, OCS.SYNONYM_ID
	, COMPONENT = OCS.MNEMONIC
	, OS.ORDER_SENTENCE_DISPLAY_LINE
	, INTERMITTENT = EVALUATE(OCS2.INTERMITTENT_IND,1,"INTERMITTENT",0,"CONTINUOUS","CHECK VALUE")
	, ORD_SENT_ORDER_COMMENT = SUBSTRING(1, 255, LT.LONG_TEXT)
FROM 
	ORDER_CATALOG_SYNONYM OCS
	, CS_COMPONENT CSP
	, ORDER_CATALOG OC
	, ORDER_CATALOG_SYNONYM OCS2
	, ORDER_SENTENCE OS
	, LONG_TEXT LT
PLAN 
	OC WHERE OC.ACTIVITY_TYPE_CD = VALUE(UAR_GET_CODE_BY("MEANING", 106, "PHARMACY"))
	AND OC.ORDERABLE_TYPE_FLAG = 8 /*IV BUILDER*/
	AND OC.ACTIVE_IND = 1 ; ORIGINAL WAS 1
JOIN 
	OCS2 WHERE OCS2.CATALOG_CD = OC.CATALOG_CD
JOIN 
	CSP WHERE CSP.CATALOG_CD = OC.CATALOG_CD
	AND CSP.COMP_ID != 0
JOIN 
	OCS WHERE OCS.SYNONYM_ID = CSP.COMP_ID
JOIN 
	OS WHERE OS.ORDER_SENTENCE_ID = OUTERJOIN (CSP.ORDER_SENTENCE_ID)
JOIN 
	LT WHERE LT.LONG_TEXT_ID = OUTERJOIN(OS.ORD_COMMENT_LONG_TEXT_ID)
ORDER BY CNVTUPPER
	(OC.PRIMARY_MNEMONIC)
	, OCS.MNEMONIC
	, OS.ORDER_SENTENCE_DISPLAY_LINE
WITH 
	UAR_CODE(D)
	, MAXREC = 1000 ; LIMITS ROWS