SELECT
	P.PERSON_ID
	, PA.PERSON_ID
	, PA.PERSON_ALIAS_ID

FROM
	PERSON   P
	, (LEFT JOIN PERSON_ALIAS PA ON (P.PERSON_ID = PA.PERSON_ID))

PLAN P
JOIN PA
WHERE P.PERSON_ID = CHANGE_ME_TO_ID ; CHANGE THIS VALUE

WITH MAXREC = 10, NOCOUNTER, SEPARATOR=" ", FORMAT
