SELECT
    C.PRSNL_ID
    , C.CREDENTIAL_ID
    , C.CREDENTIAL_CD
    , C.CREDENTIAL_TYPE_CD
    , C.ACTIVE_IND
    , C.BEG_EFFECTIVE_DT_TM
    , C.END_EFFECTIVE_DT_TM
    , P.ACTIVE_IND
    , P.NAME_FULL_FORMATTED
    , P.BEG_EFFECTIVE_DT_TM
    , P.END_EFFECTIVE_DT_TM
FROM 
    PRSNL P
    , (LEFT JOIN CREDENTIAL C ON C.PRSNL_ID = P.PERSON_ID)
PLAN 
    P

JOIN 
    C
WHERE 
    C.CREDENTIAL_ID > 0
    ; YEAR(P.BEG_EFFECTIVE_DT_TM) < 2018
WITH 
    MAXREC = 500
    , TIME = 10